language: node_js
node_js:
- "0.10"
before_install:
  - gem install sass
before_script:
  - grunt build:basic
after_success: # .travis/after_success.sh
  - git config user.email "travis@cugos.org"
  - git config user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - grunt gh-pages
